### PR TITLE
Added experimental verbiage

### PR DESCRIPTION
**Pull request by paigehargrave**
Per https://github.com/docker/docs-private/issues/1037

### CODE REVIEW

**Comment by paigehargrave** [comment]
Please review https://github.com/docker/docs-private/pull/1063 for TOC entry placement - thank you!

**Comment by paigehargrave** [comment]
@anweiss - PTAL - thank you! (Two items)

**Comment by paigehargrave** [comment]
@clemenko - Didn't realize Andrew left - can you please review this info or point me to someone - thank you in advance!

**Comment by paigehargrave** [comment]
@clemenko - Can you please take a look and merge? Thank you!

**Comment by clemenko** [comment]
LGTM

**Pull request merged**
